portal-application/src/main/java/com/similan/portal/model/TaskModel.java
package com.similan.portal.model;

import java.io.Serializable;
import java.util.List;

import com.similan.service.api.collaborationworkspace.dto.basic.TaskDto;
import com.similan.service.api.collaborationworkspace.dto.key.TaskKey;
import com.similan.service.api.comment.dto.extended.CommentAndRepliesDto;

public class TaskModel implements Serializable {

	private static final long serialVersionUID = 1L;

    private TaskDto taskData;
    
    private List<CommentAndRepliesDto<TaskKey>> comments;
    
    public TaskModel(TaskDto taskData){
    	this.taskData = taskData;
    }
    
    public String getName() {
    	return taskData.getKey().getName();
    }
    
    public String getId(){
    	return taskData.getKey().getName();
    }
    
    public int hashCode() {
		return taskData.hashCode();
	}

	public boolean equals(Object other) {
		return taskData.equals(other);
	}

	public TaskDto getTaskData() {
		return taskData;
	}

	public List<CommentAndRepliesDto<TaskKey>> getComments() {
		return comments;
	}

	public void setComments(List<CommentAndRepliesDto<TaskKey>> comments) {
		this.comments = comments;
	}
	
	public int getCommentCount() {
		if (getComments() != null)
				return getComments().size();
		return 0;
	}
	
	
}

portal-application/src/main/webapp/wall/types/collabspace/COLLABORATION_WORKSPACE_ACCESSED.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
  xmlns:h="http://java.sun.com/jsf/html"
  xmlns:f="http://java.sun.com/jsf/core"
  xmlns:c="http://java.sun.com/jsp/jstl/core"
  xmlns:ui="http://java.sun.com/jsf/facelets"
  xmlns:composite="http://java.sun.com/jsf/composite/composites"
  xmlns:p="http://primefaces.org/ui" template="/wall/wallEntryLayout.xhtml">

  <ui:define name="wallEntryTitle">
       Workspace was accessed
  </ui:define>
  <ui:define name="wallEntryBody">
    <ui:include src="/wall/wallElement.xhtml">
        <ui:param name="wallElement" value="The #{wallEntry.accessedWorkspace.key.name} was accessed by #{wallEntry.accessor.displayName}" />
    </ui:include>
  </ui:define>
</ui:composition>

portal-application/src/main/webapp/wall/types/collabspace/COLLABORATION_WORKSPACE_DOCUMENT_COMMENT.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:c="http://java.sun.com/jsp/jstl/core"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:composite="http://java.sun.com/jsf/composite/composites"
	xmlns:p="http://primefaces.org/ui"
	template="/wall/wallEntryLayout.xhtml">

	<ui:define name="wallEntryTitle">
    Commented on a document</ui:define>

	<ui:define name="wallEntryBody">
		<ui:include
			src="/wall/types/collabspace/COLLABORATION_WORKSPACE_DOCUMENT_ELEMENT.xhtml">
			<ui:param name="wallElement" value="#{wallEntry}" />
			<ui:param name="wallElementContent"
				value="A comment #{wallElement.docComment.content} was posted on #{wallElement.document.key.document.name} in 
				#{wallEntry.document.key.workspace.name}" />
		</ui:include>
	</ui:define>

</ui:composition>

portal-application/src/main/webapp/wall/types/collabspace/COLLABORATION_WORKSPACE_DOCUMENT_DOWNLOADED.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:c="http://java.sun.com/jsp/jstl/core"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:composite="http://java.sun.com/jsf/composite/composites"
	xmlns:p="http://primefaces.org/ui" template="/wall/wallEntryLayout.xhtml">

	<ui:define name="wallEntryTitle">
    Downloaded a document</ui:define>
	<ui:define name="wallEntryBody">
		<ui:include
			src="/wall/types/collabspace/COLLABORATION_WORKSPACE_DOCUMENT_ELEMENT.xhtml">
			<ui:param name="wallElement" value="#{wallEntry}" />
			<ui:param name="wallElementContent"
				value="#{wallElement.document.key.document.name} was downloaded 
				from workspace #{wallEntry.document.key.workspace.name}" />
		</ui:include>
	</ui:define>
</ui:composition>

portal-application/src/main/webapp/wall/types/collabspace/COLLABORATION_WORKSPACE_DOCUMENT_ELEMENT.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:c="http://java.sun.com/jsp/jstl/core"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:composite="http://java.sun.com/jsf/composite/composites"
	xmlns:p="http://primefaces.org/ui">


	<div class="span3 documentWallIconBorder">
		<h:outputLink
			value="#{root}/collabspace/workspaceDocumentDetail.xhtml">
			<f:param name="sdoc" value="#{wallElement.document.key.id}" />
			<p:graphicImage
				value="#{authenticatedMemberInfoView.getDocumentService().getDocumentIcon(wallElement.document.key.document)}"
				width="60" height="60" />
		</h:outputLink>
	</div>

	<div class="span7">
		<div class="popover right">
			<div class="arrow"></div>
			<div class="popover-content">
				#{wallElementContent} <br />
				<span class="muted" style="color: #aaaaaa; font-size: small;">Version
					#{wallElement.documentVersion}</span><br />
			</div>
		</div>

	</div>

</ui:composition>

portal-application/src/main/webapp/wall/types/collabspace/COLLABORATION_WORKSPACE_DOCUMENT_SHARED.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
  xmlns:h="http://java.sun.com/jsf/html"
  xmlns:f="http://java.sun.com/jsf/core"
  xmlns:c="http://java.sun.com/jsp/jstl/core"
  xmlns:ui="http://java.sun.com/jsf/facelets"
  xmlns:composite="http://java.sun.com/jsf/composite/composites"
  xmlns:p="http://primefaces.org/ui" template="/wall/wallEntryLayout.xhtml">

  <ui:define name="wallEntryTitle">
    Shared a document</ui:define>
    
    <ui:define name="wallEntryBody">
		<ui:include
			src="/wall/types/collabspace/COLLABORATION_WORKSPACE_DOCUMENT_ELEMENT.xhtml">
			<ui:param name="wallElement" value="#{wallEntry}" />
			<ui:param name="wallElementContent"
				value="#{wallElement.document.key.document.name} was shared 
				by #{wallEntry.initiator.displayName}" />
		</ui:include>
	</ui:define>

</ui:composition>

portal-application/src/main/webapp/wall/types/collabspace/COLLABORATION_WORKSPACE_DOCUMENT_SHARED_ANOTHER_WORKSPACE.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:c="http://java.sun.com/jsp/jstl/core"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:composite="http://java.sun.com/jsf/composite/composites"
	xmlns:p="http://primefaces.org/ui" template="/wall/wallEntryLayout.xhtml">

	<ui:define name="wallEntryTitle">
       shared document in #{wallEntry.sharedFromSpace.name}
  </ui:define>

	<ui:define name="wallEntryBody">
		<ui:include
			src="/wall/types/collabspace/COLLABORATION_WORKSPACE_DOCUMENT_ELEMENT.xhtml">
			<ui:param name="wallElement" value="#{wallEntry}" />
			<ui:param name="wallElementContent"
				value="#{wallEntry.initiator.displayName} shared a document 
				     #{wallElement.document.key.document.name} from
	                 #{wallEntry.sharedFromSpace.name} to #{wallEntry.document.key.workspace.name}" />
		</ui:include>
	</ui:define>
</ui:composition>

portal-application/src/main/webapp/wall/types/collabspace/COLLABORATION_WORKSPACE_DOCUMENT_UNSHARED.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:c="http://java.sun.com/jsp/jstl/core"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:composite="http://java.sun.com/jsf/composite/composites"
	xmlns:p="http://primefaces.org/ui" template="/wall/wallEntryLayout.xhtml">

	<ui:define name="wallEntryTitle">
    Unshared a document</ui:define>
	<ui:define name="wallEntryBody">
		<ui:include
			src="/wall/types/collabspace/COLLABORATION_WORKSPACE_DOCUMENT_ELEMENT.xhtml">
			<ui:param name="wallElement" value="#{wallEntry}" />
			<ui:param name="wallElementContent"
				value="#{wallElement.document.key.document.name} was unshared 
				from workspace #{wallEntry.document.key.workspace.name}" />
		</ui:include>
	</ui:define>
</ui:composition>

portal-application/src/main/webapp/wall/types/collabspace/COLLABORATION_WORKSPACE_DOCUMENT_UPDATED.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:c="http://java.sun.com/jsp/jstl/core"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:composite="http://java.sun.com/jsf/composite/composites"
	xmlns:p="http://primefaces.org/ui" template="/wall/wallEntryLayout.xhtml">

	<ui:define name="wallEntryTitle">
    posted a new version of the document</ui:define>

	<ui:define name="wallEntryBody">
		<ui:include
			src="/wall/types/collabspace/COLLABORATION_WORKSPACE_DOCUMENT_ELEMENT.xhtml">
			<ui:param name="wallElement" value="#{wallEntry}" />
			<ui:param name="wallElementContent"
				value="#{wallElement.document.key.document.name} has a new version in 
				#{wallEntry.document.key.workspace.name}" />
		</ui:include>
	</ui:define>

</ui:composition>

portal-application/src/main/webapp/wall/types/collabspace/COLLABORATION_WORKSPACE_DOCUMENT_VIEWED.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:c="http://java.sun.com/jsp/jstl/core"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:composite="http://java.sun.com/jsf/composite/composites"
	xmlns:p="http://primefaces.org/ui" template="/wall/wallEntryLayout.xhtml">

	<ui:define name="wallEntryTitle">
    Viewed a document</ui:define>

	<ui:define name="wallEntryBody">
		<ui:include
			src="/wall/types/collabspace/COLLABORATION_WORKSPACE_DOCUMENT_ELEMENT.xhtml">
			<ui:param name="wallElement" value="#{wallEntry}" />
			<ui:param name="wallElementContent"
				value="#{wallElement.document.key.document.name} was viewed in 
				#{wallEntry.document.key.workspace.name}" />
		</ui:include>
	</ui:define>

</ui:composition>

portal-application/src/main/webapp/wall/types/collabspace/COLLABORATION_WORKSPACE_PARTICIPANT_JOINED.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
  xmlns:h="http://java.sun.com/jsf/html"
  xmlns:f="http://java.sun.com/jsf/core"
  xmlns:c="http://java.sun.com/jsp/jstl/core"
  xmlns:ui="http://java.sun.com/jsf/facelets"
  xmlns:composite="http://java.sun.com/jsf/composite/composites"
  xmlns:p="http://primefaces.org/ui" template="/wall/wallEntryLayout.xhtml">

  <ui:define name="wallEntryTitle">
    Joined</ui:define>
  <ui:define name="wallEntryBody">
    <ui:include src="/wall/wallElement.xhtml">
      <ui:param name="wallElement" value="Joined collabspace #{wallEntry.participation.key.workspace.name}" />
    </ui:include>
  </ui:define>
</ui:composition>

portal-application/src/main/webapp/wall/types/collabspace/COLLABORATION_WORKSPACE_TASK_CREATED.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
  xmlns:h="http://java.sun.com/jsf/html"
  xmlns:f="http://java.sun.com/jsf/core"
  xmlns:c="http://java.sun.com/jsp/jstl/core"
  xmlns:ui="http://java.sun.com/jsf/facelets"
  xmlns:composite="http://java.sun.com/jsf/composite/composites"
  xmlns:p="http://primefaces.org/ui" template="/wall/wallEntryLayout.xhtml">

  <ui:define name="wallEntryTitle">
    Created a task</ui:define>
  <ui:define name="wallEntryBody">
    <ui:include src="/wall/wallElement.xhtml">
      <ui:param name="wallElement" value="A new #{wallEntry.task.key.name} task was created in collabspace #{wallEntry.task.key.workspace.name}" />
    </ui:include>
  </ui:define>
</ui:composition>

portal-application/src/main/webapp/wall/types/collabspace/NEWS_POST_WALL_ENTRY.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:c="http://java.sun.com/jsp/jstl/core"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:composite="http://java.sun.com/jsf/composite/composites"
	xmlns:p="http://primefaces.org/ui"
	template="/wall/wallEntryLayout.xhtml">

	<ui:define name="wallEntryTitle">
    Shared Information </ui:define>

	<ui:define name="wallEntryBody">
		<ui:include src="/news/news.xhtml">
			<ui:param name="news" value="#{wallEntry.news}" />
		</ui:include>
	</ui:define>
</ui:composition>