portal-application/src/main/java/com/similan/portal/model/DocumentInstanceAndDocumentModel.java
package com.similan.portal.model;

import java.io.Serializable;
import java.net.URLEncoder;

import com.similan.service.api.document.dto.extended.DocumentInstanceAndDocumentDto;
import com.similan.service.api.document.dto.extended.DocumentStatisticsDto;
import com.similan.service.api.document.dto.key.DocumentInstanceKey;

public class DocumentInstanceAndDocumentModel implements Serializable {

  private static final long serialVersionUID = -1613814314887775015L;
  private DocumentInstanceAndDocumentDto data;
  private boolean selected = false;
  private boolean checkedOut = false;
  private boolean checkedOutByUser = false;
  private String documentStorageKey;
  private DocumentStatisticsDto statistics;

  public DocumentInstanceAndDocumentModel(DocumentInstanceAndDocumentDto data) {
    this.data = data;
  }

  public DocumentInstanceAndDocumentModel(DocumentInstanceAndDocumentDto data,
      boolean selected) {
    this.data = data;
    this.selected = selected;
  }

  public String getName() {
    return data.getKey().getDocument().getName();
  }

  public DocumentInstanceKey getKey() {
    return data.getKey();
  }

  @Override
  public String toString() {
    return "DocumentInstanceAndDocumentModel [data=" + data + ", selected="
        + selected + ", checkedOut=" + checkedOut + ", checkedOutByUser="
        + checkedOutByUser + ", documentStorageKey=" + documentStorageKey
        + ", statistics=" + statistics + "]";
  }

  public int hashCode() {
    return data.hashCode();
  }

  public boolean equals(Object other) {
    return data.equals(other);
  }

  public boolean isSelected() {
    return selected;
  }

  public void setSelected(boolean selected) {
    this.selected = selected;
  }

  public DocumentInstanceAndDocumentDto getData() {
    return data;
  }

  public boolean isCheckedOut() {
    return checkedOut;
  }

  public void setCheckedOut(boolean checkedOut) {
    this.checkedOut = checkedOut;
  }

  public boolean isCheckedOutByUser() {
    return checkedOutByUser;
  }

  public void setCheckedOutByUser(boolean checkedOutByUser) {
    this.checkedOutByUser = checkedOutByUser;
  }

  public DocumentStatisticsDto getStatistics() {
    return statistics;
  }

  public void setStatistics(DocumentStatisticsDto statistics) {
    this.statistics = statistics;
  }

  public String getPageStorageKey() {
    // {workspaceOwnerName}/{workspaceName}/{documentName}/{documentInstanceVersion}/{number}",
    // method = RequestMethod.GET
    if (documentStorageKey == null) {
      try {
        StringBuilder builder = new StringBuilder();
        builder
            .append(
                data.getKey().getDocument().getWorkspace().getOwner().getName())
            .append('/')
            .append(
                URLEncoder.encode(data.getKey().getDocument().getWorkspace()
                    .getName(), "ISO-8859-1"))
            .append('/')
            .append(
                URLEncoder.encode(data.getKey().getDocument().getName(),
                    "ISO-8859-1")).append('/')
            .append(data.getKey().getVersion());

        documentStorageKey = builder.toString();
      } catch (Exception e) {
        documentStorageKey = "";
      }
    }
    return documentStorageKey;
  }
}

portal-application/src/main/webapp/docview/default.xhtml
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
  xmlns:h="http://java.sun.com/jsf/html" xmlns:f="http://java.sun.com/jsf/core"
  xmlns:ui="http://java.sun.com/jsf/facelets"
  xmlns:custom="http://www.businessreach.com/custom"
  xmlns:p="http://primefaces.org/ui">

  
  <div class="old-content">
       <h:form id="formPage" prependId="true" enctype="multipart/form-data">
	   
		  <p:panel id="documentDetailContentPanel" styleClass="noBorder"
			rendered="#{not empty documentView.pages}">

			<h:panelGrid columns="1" styleClass="noBorder">

			  <p:dataGrid id="pageThumbnailTable" var="page"
				value="#{documentView.pages}" paginator="true"
				rows="1" columns="1" paginatorAlwaysVisible="false"
				paginatorPosition="bottom" styleClass="ui-datagrid-no-border">

				<p:panel id="documentDetailContentItemPanel"
				  styleClass="documentPageBorder">

					<p:graphicImage
					  value="/spring/documentpage/thumbnail/#{page.pageStorageKey}"
					  width="700" />
					  
				</p:panel>

			  </p:dataGrid>
			</h:panelGrid>
		  </p:panel>
  
      </h:form>
    </div>
	
</ui:composition>

portal-application/src/main/webapp/docview/documentViewer.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
  xmlns:h="http://java.sun.com/jsf/html" xmlns:f="http://java.sun.com/jsf/core"
  xmlns:c="http://java.sun.com/jsp/jstl/core"
  xmlns:ui="http://java.sun.com/jsf/facelets"
  xmlns:composite="http://java.sun.com/jsf/composite/composites"
  xmlns:p="http://primefaces.org/ui">

  <ui:param name="viewerId"
    value="#{documentView.getViewerId()}" />

  <ui:fragment rendered="#{viewerId == 'generic-crocodoc'}">
    <ui:include src="generic-crocodoc.xhtml">
    </ui:include>
  </ui:fragment>
  <ui:fragment rendered="#{viewerId == 'generic-box'}">
    <ui:include src="generic-box.xhtml">
    </ui:include>
  </ui:fragment>
  <ui:fragment
    rendered="#{viewerId == 'generic-jodconverter' || viewerId == 'ooxml-presentation-poi' || viewerId == 'ms-powerpoint-poi' || viewerId == 'pdf-pdfbox' || viewerId == 'image-awt'}">
    <ui:include src="default.xhtml">
    </ui:include>
  </ui:fragment>

</ui:composition>

portal-application/src/main/webapp/docview/generic-box.xhtml
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:custom="http://www.businessreach.com/custom"
	xmlns:p="http://primefaces.org/ui">

  <iframe style="width: 100%; height: 900px;" 
      src="https://view-api.box.com/1/sessions/#{documentView.generateBoxToken()}/view?theme=dark" allowfullscreen=""/>
</ui:composition>

portal-application/src/main/webapp/docview/generic-crocodoc.xhtml
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:custom="http://www.businessreach.com/custom"
	xmlns:p="http://primefaces.org/ui">

	<iframe style="width: 100%; height: 900px;"
		src="https://crocodoc.com/view/#{documentView.generateCrocodocToken()}" />
</ui:composition>