portal-application/src/main/java/com/similan/portal/model/SelectableContact.java
package com.similan.portal.model;

import java.io.Serializable;

import com.similan.domain.entity.community.PhotoViewOption;
import com.similan.service.api.community.dto.basic.MemberDto;
import com.similan.service.api.community.dto.basic.SocialActorContactDto;
import com.similan.service.api.community.dto.basic.SocialActorType;
import com.similan.service.api.connection.dto.basic.ContactType;

public class SelectableContact implements Serializable {

  private static final long serialVersionUID = 6228084429066853530L;
  private SocialActorContactDto contact;
  private boolean selected = false;
  private ContactSource contactSource = ContactSource.Business;

  public SelectableContact(SocialActorContactDto contact) {
    this.contact = contact;
  }

  public String getImagePath() {
    return PhotoViewOption.ShowPhoto.effectivePhoto(
        "/images/memberDefaultPhoto.png", contact.getContact()
            .getDisplayImage());
  }

  public Long getId() {
    return contact.getContact().getId();
  }

  public SocialActorContactDto getContact() {
    return contact;
  }

  public void setContact(SocialActorContactDto contact) {
    this.contact = contact;
  }

  public String getFullName() {
    return contact.getContact().getDisplayName();
  }

  public String getCompany() {
    return contact.getContact().equals(SocialActorType.Member) ?
        ((MemberDto)contact.getContact()).getEmployer() : "";
  }

  public ContactType getContactType() {
    return contact.getType();
  }

  public String getContactCategory() {
    return contact.getType().toString();
  }

  public boolean getIsBusiness() {
    if (contact.getContact().getType().equals(SocialActorType.Business)) {
      return true;
    }
    return false;
  }

  public boolean getIsMember() {
    if (contact.getContact().getType().equals(SocialActorType.Member)) {
      return true;
    }
    return false;
  }

  public String getEmail() {
    return contact.getContact().getContactEmail();
  }

  public boolean isSelected() {
    return selected;
  }

  public void setSelected(boolean selected) {
    this.selected = selected;
  }

  public ContactSource getContactSource() {
    return contactSource;
  }

  public void setContactSource(ContactSource contactSource) {
    this.contactSource = contactSource;
  }

}

portal-application/src/main/java/com/similan/portal/model/TaskModel.java
package com.similan.portal.model;

import java.io.Serializable;
import java.util.List;

import com.similan.service.api.collaborationworkspace.dto.basic.TaskDto;
import com.similan.service.api.collaborationworkspace.dto.key.TaskKey;
import com.similan.service.api.comment.dto.extended.CommentAndRepliesDto;

public class TaskModel implements Serializable {

	private static final long serialVersionUID = 1L;

    private TaskDto taskData;
    
    private List<CommentAndRepliesDto<TaskKey>> comments;
    
    public TaskModel(TaskDto taskData){
    	this.taskData = taskData;
    }
    
    public String getName() {
    	return taskData.getKey().getName();
    }
    
    public String getId(){
    	return taskData.getKey().getName();
    }
    
    public int hashCode() {
		return taskData.hashCode();
	}

	public boolean equals(Object other) {
		return taskData.equals(other);
	}

	public TaskDto getTaskData() {
		return taskData;
	}

	public List<CommentAndRepliesDto<TaskKey>> getComments() {
		return comments;
	}

	public void setComments(List<CommentAndRepliesDto<TaskKey>> comments) {
		this.comments = comments;
	}
	
	public int getCommentCount() {
		if (getComments() != null)
				return getComments().size();
		return 0;
	}
	
	
}

portal-application/src/main/webapp/lead/activeOrgLeadManagement.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:c="http://java.sun.com/jsp/jstl/core"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:composite="http://java.sun.com/jsf/composite/composites"
	xmlns:p="http://primefaces.org/ui">
    
    <ui:include src="/lead/leadSubmissionDialog.xhtml" />
    <ui:include src="/lead/addNewLeadDialog.xhtml" />
    
    <p:confirmDialog id="leadTransferStartDialog" 
         message="The lead synchronization process between CRM and Lead Exchange Portal has started. An email will be sent when sync process is done"  
         header="Lead Sync" severity="alert" widgetVar="leadTransferStart">  
        <p:commandButton id="syncConfirm" value="OK" 
	     actionListener="#{organizationLeadView.performCrmSync}" 
	     update="leadPanel"
	     oncomplete="leadTransferStart.hide()"/>  
    </p:confirmDialog>
    
    <p:confirmDialog id="deleteLeadDialog" message="Are you sure to delete leads?"  
                header="Delete Lead" severity="alert" widgetVar="dlgDeleteLead">  
                  
        <p:commandButton id="deleteConfirm" value="Yes" 
                         oncomplete="dlgDeleteLead.hide()"  
                         actionListener="#{organizationLeadView.deleteLeads}"
                         update="leadPanel"/>  
        <p:commandButton id="deleteCancel" value="No" 
                         onclick="dlgDeleteLead.hide()" type="button" />   
                  
    </p:confirmDialog>
    
    <p:panel style="background:rgb(252,244,254)">
    
        <h:panelGrid>
          <h:panelGroup>
             <p:commandButton id="addNewLeadBtn" oncomplete="dlgAddLead.show()" 
                             value="Add" icon="ui-icon-plus" 
		                     style="margin-right:5px; margin-bottom:10px; float:right"/> 
		     <p:tooltip for="addNewLeadBtn" value="Add a new lead" 
				                    showEffect="fade" hideEffect="fade" /> 
				                    
             <p:commandButton id="leadSendPartnerBtn" oncomplete="dlgLeadSubmit.show()" 
                             value="Transfer" icon="ui-icon-person" 
		                     style="margin-right:5px; margin-bottom:10px; float:right"/> 
		     <p:tooltip for="leadSendPartnerBtn" value="Assign to partner" 
				                    showEffect="fade" hideEffect="fade" />
				                    
		     <p:commandButton id="activeLeadAssignCrmBtn" 
                             icon="ui-icon-extlink" value="Crm Sync"
		                     style="margin-right:5px; margin-bottom:10px; float:right" 
				      oncomplete="leadTransferStart.show()"/>	
				     
		     <p:tooltip for="activeLeadAssignCrmBtn" value="Synchronize with CRM" 
	                    showEffect="fade" hideEffect="fade" />
	                    
	         <p:commandButton id="deleteLeadBtn" oncomplete="dlgDeleteLead.show()" 
                             icon="ui-icon-close" value="Delete"
		                     style="margin-right:5px; margin-bottom:10px; float:right"/> 
		     <p:tooltip for="deleteLeadBtn" value="Delete selected leads" 
				                    showEffect="fade" hideEffect="fade" />  
          
          </h:panelGroup>
        </h:panelGrid>
        
	    <h:panelGrid columns="2">
			<p:selectOneMenu id="leadFilterRefreshOption" value="#{organizationLeadView.leadFilterRefreshOption}" 
			                 style="margin-bottom:10px">
				<f:selectItem itemLabel="All" itemValue="All" />  
		        <f:selectItem itemLabel="New Leads" itemValue="New" />  
		        <f:selectItem itemLabel="Transferred Leads" itemValue="Transferred" />
		    </p:selectOneMenu>
		    
		    <p:commandButton  id="leadFilterRefreshBtn" icon="ui-icon-search" 
		                      actionListener="#{organizationLeadView.updateDataTable}" 
	                             process="@this leadFilterRefreshOption" update="tabLeadManagementDetail:leadPanel"
	                             style="margin-bottom:10px"/> 
	    </h:panelGrid>
    </p:panel>
    
    <p:spacer height="10"/>
    
   	<p:dataTable id="leadPanel" var="lead" paginator="true" paginatorPosition="bottom" 
   	               paginatorAlwaysVisible="false" rows="10" draggableColumns="true"
   	               value="#{organizationLeadView.leadModel}"
   	               selection="#{organizationLeadView.selectedLeads}" 
   	               rowStyleClass="#{lead.viewed eq false ? 'unOpenedLead' : 'openedLead'}">
   	               
          <p:column selectionMode="multiple" style="width:18px" styleClass="buttomBorderBlack" /> 
          
		  <p:column id="leadType" style="width:20px" headerText="Type" styleClass="buttomBorderBlack">
	            <p:graphicImage id="contactLeadIcon" rendered="#{lead.leadTypeStr eq 'ContactLead'}" 
	                            value="/images/monoicons/userIcon24.png" 
	                            width="20" height="20" />
	            <p:tooltip rendered="#{lead.leadTypeStr eq 'ContactLead'}" 
	                       for="contactLeadIcon" value="Contact lead" 
	                    showEffect="fade" hideEffect="fade" />
	                    
	            <p:graphicImage id="clickThroughLeadIcon" rendered="#{lead.leadTypeStr eq 'ClickThroughLead'}" 
	                            value="/images/monoicons/zoomIcon24.png" 
	                            width="20" height="20" />
	            <p:tooltip for="clickThroughLeadIcon" rendered="#{lead.leadTypeStr eq 'ClickThroughLead'}" 
	                    value="Click through lead" 
	                    showEffect="fade" hideEffect="fade" />
	                            
	            <p:graphicImage id="searchLeadIcon" rendered="#{lead.leadTypeStr eq 'SearchLead'}" 
	                            value="/images/monoicons/zoomIcon24.png" 
	                            width="20" height="20" />
	            <p:tooltip for="searchLeadIcon" rendered="#{lead.leadTypeStr eq 'SearchLead'}" 
	                       value="Search lead" 
	                       showEffect="fade" hideEffect="fade" />
	                            
	            <p:graphicImage id="acquiredLeadIcon" rendered="#{lead.leadTypeStr eq 'AcquiredLead'}" 
	                            value="/images/monoicons/acquiredLeadIcon24.png" 
	                            width="20" height="20" />
	            <p:tooltip for="acquiredLeadIcon" rendered="#{lead.leadTypeStr eq 'AcquiredLead'}" 
	                       value="Acquired lead" 
	                       showEffect="fade" hideEffect="fade" />
	                            
	            <p:graphicImage id="transferLeadIcon" rendered="#{lead.leadTypeStr eq 'TransferLead'}" 
	                            value="/images/monoicons/transferLeadIcon24.png" 
	                            width="20" height="20" />
	            <p:tooltip for="transferLeadIcon" rendered="#{lead.leadTypeStr eq 'TransferLead'}" 
	                    value="Transferred lead" 
	                    showEffect="fade" hideEffect="fade" />
	                            
	            <p:graphicImage id="unknownLeadIcon" rendered="#{lead.leadTypeStr eq 'Unknown'}" 
	                            value="/images/monoicons/unknownLeadIcon24.png" 
	                            width="20" height="20" />
	            <p:tooltip for="unknownLeadIcon" rendered="#{lead.leadTypeStr eq 'Unknown'}" 
	                       value="Unknown lead" 
	                    showEffect="fade" hideEffect="fade" />
	      </p:column>
		  
	      <p:column id="leadSource" style="width:50px" headerText="Lead Name" styleClass="buttomBorderBlack"
	                filterBy="#{lead.firstName}" filterMatchMode="startsWith" sortBy="#{lead.firstName}">	            
	            <h:outputText value="#{lead.firstName} #{lead.lastName}" />
	            <br />
	            <h:outputText value="#{lead.company}" />
				<br />
				<h:outputText value="#{lead.name}" />
	      </p:column>
	      
	      <p:column id="leadSourcePhone" style="width:150px" headerText="Contact" styleClass="buttomBorderBlack"
	                filterBy="#{lead.contactPhone}" filterMatchMode="startsWith" sortBy="#{lead.contactPhone}">
	            <h:outputText rendered="#{!empty lead.contactPhone}" value="Phone #{lead.contactPhone}" />
				<br/>
				<h:outputText rendered="#{!empty lead.contactEmail}" value="Email #{lead.contactEmail}" />
				<br/>
				<h:outputText rendered="#{!empty lead.location.zipCode}" value="Zipcode #{lead.location.zipCode}" />
	      </p:column>
	      
	      <p:column id="leadSourceDate" style="width:50px" headerText="Date" styleClass="buttomBorderBlack"
	                filterBy="#{lead.timeStamp}" filterMatchMode="startsWith" sortBy="#{lead.timeStamp}">
	            <h:outputText value="#{lead.timeStamp}">
	                <f:convertDateTime pattern="MM/dd/yyyy" />
	            </h:outputText>
	      </p:column>
	      
	      <p:column id="leadSourceAction" style="width:80px" headerText="Action" styleClass="buttomBorderBlack">
			<h:outputLink value="#{root}/lead/viewLeadDetail.xhtml" rendered="#{lead.transferState == null or lead.transferState == 'None' or lead.transferState == 'Accepted'}">
				<f:param name="lid" value="#{lead.id}" />
				<f:param name="ldtype" value="#{lead.leadTypeStr}" />
				<p:graphicImage id="viewResultsButton"
								value="/images/monoicons/zoomIcon24.png" 
								width="20" height="20" />
			</h:outputLink>
			<h:commandLink id="transferLeadApproveLink"
				actionListener="#{organizationLeadView.approveLeadTransfer(lead.id)}"
				rendered="#{lead.transferState != null and lead.transferState == 'Pending'}" style="margin-right: 10px">
				<f:ajax execute="@this" render="leadPanel" />
				<p:graphicImage id="approveTransferLeadButton"
					value="/images/monoicons/checkMarkIcon24.png" width="15"
					height="15" />
			</h:commandLink>
			<p:tooltip
				rendered="#{lead.transferState != null and lead.transferState == 'Pending'}"
				for="transferLeadApproveLink" value="Accept lead" showEffect="fade"
				hideEffect="fade" />
			<h:commandLink id="transferLeadRejectLink"
				actionListener="#{organizationLeadView.rejectLeadTransfer(lead.id)}"
				rendered="#{lead.transferState != null and lead.transferState == 'Pending'}">
				<f:ajax execute="@this" render="leadPanel" />
				<p:graphicImage id="rejectTransferLeadButton"
					value="/images/monoicons/deleteIcon24.png" width="15" height="15" />
			</h:commandLink>
			<p:tooltip
				rendered="#{lead.transferState != null and lead.transferState == 'Pending'}"
				for="transferLeadRejectLink" value="Reject lead" showEffect="fade"
				hideEffect="fade" />

		</p:column>
	  </p:dataTable>

</ui:composition>

portal-application/src/main/webapp/lead/addNewLeadDialog.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:c="http://java.sun.com/jsp/jstl/core"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:p="http://primefaces.org/ui">
	
	<p:dialog id="addNewLeadDialog" resizable="false" modal="true" showEffect="explode" 
	                     header="Add New Lead" widgetVar="dlgAddLead" >
       <p:outputPanel id="addNewLeadPanel" layout="block" >
         <h:panelGrid style="margin-top:10px;" columns="2">
         
            <h:outputLabel for="firstName" value="First Name "/>
	        <p:inputText id="firstName" 
	                   value="#{organizationLeadView.newLeadDto.firstName}" 
	                   style="margin-bottom:5px" size="30"/>
	        
	        <h:outputLabel for="lastName" value="Last Name "/>
	        <p:inputText id="lastName" 
	                   value="#{organizationLeadView.newLeadDto.lastName}" 
	                   style="margin-bottom:5px" size="30"/>
	                   
	        <h:outputLabel for="company" value="Company "/>
	        <p:inputText id="company" 
	                   value="#{organizationLeadView.newLeadDto.company}" 
	                   style="margin-bottom:5px" size="30"/>	                   
	        
	        <h:outputLabel for="contactPhone" value="Phone "/>
	        <p:inputText id="contactPhone" 
	                   value="#{organizationLeadView.newLeadDto.contactPhone}" 
	                   style="margin-bottom:5px" size="30"/>
	        
	        <h:outputLabel for="contactEmail" value="Email "/>
	        <p:inputText id="contactEmail" 
	                   value="#{organizationLeadView.newLeadDto.contactEmail}" 
	                   style="margin-bottom:5px" size="30"/>
	                   
	        <h:outputLabel for="leadStreet" value="Street "/>
	        <p:inputText id="leadStreet" 
	                     value="#{organizationLeadView.newLeadDto.location.street}" 
	                     style="margin-bottom:5px" size="30"/>
	        
	        <h:outputLabel for="leadCity" value="City "/>
	        <p:inputText id="leadCity" 
	                     value="#{organizationLeadView.newLeadDto.location.city}" 
	                     style="margin-bottom:5px" size="30"/>
	        
	        <h:outputLabel for="selectCountry" value="Country "/>
			<p:selectOneMenu id="selectCountry"
				style="width: 250px;margin-bottom:10px;margin-top:10px"
				effect="fade" filter="true" filterMatchMode="startsWith"
				value="#{organizationLeadView.newLeadDto.location.country}">
				<f:selectItem itemLabel="Select One..." itemValue="#{null}" />
				<f:selectItems value="#{countryBean.countryList}" var="countryType"
					itemLabel="#{countryType.countryName}"
					itemValue="#{countryType.countryName}" />
				<p:ajax update="stateSelectList" execute="@this"
					listener="#{organizationLeadView.loadStatesForSelectedCountry}" />
			</p:selectOneMenu>
	
			<h:outputLabel for="stateSelectList" value="State: "/>
			<p:selectOneMenu id="stateSelectList"
				style="margin-bottom:10px;margin-top:10px" effect="fade"
				filter="true" filterMatchMode="startsWith"
				value="#{organizationLeadView.newLeadDto.location.state}">
				<f:selectItem itemLabel="Select One..." itemValue="#{null}" />
				<f:selectItems value="#{organizationLeadView.selectedStateList}"
					var="stateType" itemLabel="#{stateType.stateName}"
					itemValue="#{stateType.stateName}" />
			</p:selectOneMenu>

				<h:outputLabel for="leadZipCode" value="Zip "/>
	        <p:inputText id="leadZipCode" 
	               value="#{organizationLeadView.newLeadDto.location.zipCode}" size="30"/>
	        
         </h:panelGrid>
          	  <p:commandButton  value="Add" id="addNewLeadDialogBtn" 
          	                    action="#{organizationLeadView.addNewLead}" onclick="dlgAddLead.hide()" 
          	                    process="@this addNewLeadPanel" 
	                            update="tabLeadManagementDetail" style="margin-left:10px;margin-top:10px"/>
       </p:outputPanel>
	</p:dialog>
</ui:composition>

portal-application/src/main/webapp/lead/leadAddKeywordsFilter.xhtml
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:custom="http://www.businessreach.com/custom"
	xmlns:p="http://primefaces.org/ui">
	
	 <h:outputLabel for="leadSearchFilterOutputPanel" value="Keywords "/>
     <p:outputPanel id="leadSearchFilterOutputPanel" autoUpdate="true">
     
	     <p:panel style="margin-bottom:20px;margin-top:20px;width:325px">
	     <p:panel id="leadSearchFilterTextPanel" style="margin-bottom:2px;border:hidden">
		     <p:inputText id="leadSearchFilterText" value="#{leadViewSettingsView.keywordToAdd}"  size="35"/>
		     <p:commandButton id="leadSearchFilterBtn" icon="ui-icon-plus"
		                action="#{leadViewSettingsView.addKeyword}" style="width:20px;height:20px;margin-left:10px;" 
		                process="@this leadSearchFilterOutputPanel" update="leadSearchFilterOutputPanel"/> 
		     <p:tooltip for="leadSearchFilterBtn" value="Add a new keyword" 
				                    showEffect="fade" hideEffect="fade" />
	     </p:panel>
	     
	     <p:panel id="leadSearchFilterPanel" 
	              style="width:265px;border-style:hidden">
	      
	        <p:dataGrid id="leadSearchFilterDataTable" value="#{leadViewSettingsView.leadSetting.keywordFilters}" 
		                       var="leadSearchKeywordFilter" emptyMessage="" columns="4" styleClass="ui-datagrid-no-border">
	            <p:panel style="border:hidden">
	                <h:panelGroup>
		               <h:outputText value="#{leadSearchKeywordFilter.keyword}" />
		               <p:commandLink action="#{leadViewSettingsView.deleteKeyword(leadSearchKeywordFilter.keyword)}" 
		                              update="leadSearchFilterDataTable">
		                  <h:outputText styleClass="ui-icon ui-icon-closethick" />
		               </p:commandLink>
	               </h:panelGroup>
	            </p:panel> 
	        </p:dataGrid>
	      </p:panel>
	      
	     </p:panel>
	</p:outputPanel>

</ui:composition>

portal-application/src/main/webapp/lead/leadAlertSettings.xhtml
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:custom="http://www.businessreach.com/custom"
	xmlns:composite="http://java.sun.com/jsf/composite/composites"
	xmlns:p="http://primefaces.org/ui"
	template="/templates/basemenulayout.xhtml">

	<ui:define name="title">Lead Alert Settings</ui:define>
	<ui:define name="centerContent">
	
	<p:spacer height="10"/>
	<ui:include src="/templates/menu/leadManagementMenu.xhtml" />
	<p:spacer height="10"/>
	
	<h3>Alert Settings</h3>  
	<h:panelGrid id="alertSettingOptions" columns="2" style="margin-bottom:10px" cellpadding="5"> 
	   
	   <h:outputText value="Enable All Alerts "/>
	   <p:selectBooleanCheckbox value="#{leadAlertSettingView.leadAlertSettings.all}" />
	   
	   <h:outputText value="Send Alert when new Leads Arrive "/>
	   <p:selectBooleanCheckbox value="#{leadAlertSettingView.leadAlertSettings.newLeadArrival}" />
	   
	   <h:outputText value="Send Alert when new Transfers arrive "/>
	   <p:selectBooleanCheckbox value="#{leadAlertSettingView.leadAlertSettings.newLeadTransfer}" />
	   
	   <h:outputText value="Send Alert when Member updates my leads "/>
	   <p:selectBooleanCheckbox value="#{leadAlertSettingView.leadAlertSettings.memberLeadUpdate}" />
	   
	   <h:outputText value="Email Alert "/>
	   <p:selectBooleanCheckbox value="#{leadAlertSettingView.leadAlertSettings.alertViaEmail}" />
	   
	   <h:outputText value="SMS Alert "/>
	   <p:selectBooleanCheckbox value="#{leadAlertSettingView.leadAlertSettings.alertViaSms}" />
	</h:panelGrid>
	<p:commandButton  id="alertSettingSaveBtn" value="Save" action="#{leadAlertSettingView.save}" 
                            process="@this alertSettingOptions"
                            style="margin-top:10px;"/>  
	</ui:define>	
	<ui:define name="leftNavigationBar">
		<ui:include src="/component/leftNavigationBar.xhtml" />
	</ui:define>
	
</ui:composition>

portal-application/src/main/webapp/lead/leadReports.xhtml
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:custom="http://www.businessreach.com/custom"
	xmlns:composite="http://java.sun.com/jsf/composite/composites"
	xmlns:p="http://primefaces.org/ui"
	template="/templates/basemenulayout.xhtml">

	<ui:define name="title">Lead Settings</ui:define>
	<ui:define name="centerContent">
	
	  <p:spacer height="10"/>
	  <ui:include src="/templates/menu/leadManagementMenu.xhtml" />
	  <p:spacer height="20"/>
	  
          VIEW LEAD REPORTS
          
    </ui:define>
	<ui:define name="leftNavigationBar">
		<ui:include src="/component/leftNavigationBar.xhtml" />
	</ui:define>
</ui:composition>

portal-application/src/main/webapp/lead/leadSubmissionDialog.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:c="http://java.sun.com/jsp/jstl/core"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:p="http://primefaces.org/ui">
	
	 <p:dialog id="leadSubmissionDialog" resizable="false" modal="true" showEffect="explode" 
	                     header="Assign Leads" widgetVar="dlgLeadSubmit">
       <p:outputPanel id="leadSubmissionPanel" layout="block">
           
           <p:dataTable id="leadContactDataTable" var="leadContact" paginator="true" paginatorPosition="bottom" 
   	                paginatorAlwaysVisible="false" rows="10"
	                value="#{organizationLeadView.leadContacts}" 
	                rowKey="#{leadContact.id}" 
	                selection="#{organizationLeadView.selectedContacts}">
	                
	            <p:column selectionMode="multiple" style="width:18px" styleClass="buttomBorder" />
	            
	            <p:column id="leadContactImage" style="width:50px" styleClass="buttomBorder">
	                 <p:graphicImage  value="/spring/assets#{leadContact.imagePath}" 
	   	                     width="40" height="40" />
   	            </p:column>
   	            
	            <p:column id="leadContactInfo" style="width:50px" styleClass="buttomBorder"
	                    filterBy="#{leadContact.fullName}" filterMatchMode="startsWith" sortBy="#{leadContact.fullName}">
	                 <h:outputText value="#{leadContact.fullName}" />
	            </p:column>
	            
	            <p:column id="leadContactEmail" style="width:50px" styleClass="buttomBorder"
	                    filterBy="#{leadContact.email}" filterMatchMode="startsWith" sortBy="#{leadContact.email}">
	   	             <h:outputText value="#{leadContact.email}" /> 
	            </p:column>	
	                        
	        </p:dataTable>	
	       
            <p:commandButton id="leadAssignBtn" oncomplete="dlgLeadSubmit.hide();leadSubmissionConfirmationDialogVar.show()" value="Assign" icon="ui-icon-check" 
			                     action="#{organizationLeadView.assignLead}" 
			                     style="margin-right:5px;margin-top:5px">
			</p:commandButton>
			<p:tooltip for="leadAssignBtn" value="Click to assign lead to the selected contacts" 
			                               showEffect="fade" hideEffect="fade" />
       </p:outputPanel>
     </p:dialog>

	<p:confirmDialog id="leadSubmissionConfirmationDialog"
		message="An email has been sent to the selected partners to approval of transfer."
		header="Assign Leads" severity="alert" widgetVar="leadSubmissionConfirmationDialogVar">
		<p:commandButton id="assignConfirm" value="OK"
			oncomplete="leadSubmissionConfirmationDialogVar.hide()" />
	</p:confirmDialog>

</ui:composition>